### PR TITLE
Take culture into account when showing and adding redirects

### PR DESCRIPTION
**Pull request by creativesuspects**
Solves #14

### CODE REVIEW

**Comment by dawoe** [comment]
Hi @creativesuspects 

Are you still working on this one ? Or can I start testing this one ?

Dave

**Comment by creativesuspects** [comment]
Hi @dawoe,

I was running into some issues on a single language configuration or when there were no 'Culture and Hostnames' configured. These issues should now have been resolved. So yes, please go ahead and test the changes.

Arjan

**Comment by GeorgeTheEnthusiast** [comment]
I am also interested in this feature :) By any chance, do you know @dawoe when you would finish testing it?

**Comment by kamilbuczek** [comment]
I keep my fingers crossed for the new release! We really need support for multi-language redirection support! @dawoe  what are your plans to release the new version?

**Comment by ismailmayat** [comment]
@creativesuspects i am just working on new feature to raise events when redirect is created  or deleted I have got that working, I also need culture stuff working I have merged your branch into mine and am going to test.  Is it worth putting through as one new combined PR?  See https://github.com/ismailmayat/umbraco-redirectsviewer/tree/culture

**Comment by dawoe** [comment]
hi @creativesuspects 

Thanks for the PR. This is merged and available in the latests beta

**Pull request merged**
